### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by alecrabbit**
> UPD. Sorry for so many commits. Just couldn't stop myself from coding )

### These changes are unbreaking

my PR suggests:
### Add
 - adding new protected method `checkIfTerminalColorIsSupported()` called from `__construct()` to set `$this->isSupported` var
### Change
- method `isSupported()` now returns value of `$this->isSupported`

### Tests output
```
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

.....................

Time: 56 ms, Memory: 4.50MB

OK (21 tests, 25 assertions)
```
### Details
Method `isSupported()` called each time we apply style to text - [ConsoleColor.php:Line86](https://github.com/JakubOnderka/PHP-Console-Color/blob/f725c01cfd5c29005919850c1502066149dc1117/src/ConsoleColor.php#L86)
```php
   if (!$this->isStyleForced() && !$this->isSupported()) {
```
but every time we do  this method checks terminal for color support
```php
public function isSupported()
    {
        if (DIRECTORY_SEPARATOR === '\\') {
            if (function_exists('sapi_windows_vt100_support') && @sapi_windows_vt100_support(STDOUT)) {
                return true;
            } elseif (getenv('ANSICON') !== false || getenv('ConEmuANSI') === 'ON') {
                return true;
            }
            return false;
        } else {
            return function_exists('posix_isatty') && @posix_isatty(STDOUT);
        }
    }
```

### CODE REVIEW

**Comment by alecrabbit** [comment]
also, you can consider adding `.gitattributes` file
it minimizes release archive file size by getting rid of unnecessary files

**Comment by alecrabbit** [comment]
I've added `build.xml` and `example.php` to `.gitattributes`

**Comment by alecrabbit** [comment]
made more optimizations

**Comment by alecrabbit** [comment]
more refactoring
and it's still unbreaking changes

**Comment by alecrabbit** [comment]
@JakubOnderka any progress? :smile:

**Comment by GrahamCampbell** [comment]
This repo is now abandoned.

**Comment by alecrabbit** [comment]
abandoned indeed

**Pull request closed without merging**
